version: "3"

services:
  postgres:
    container_name: postgres-go
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $PG_USER -d $PG_DB" ]
      interval: 5s
      start_period: 3s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "$PG_USER"
      POSTGRES_PASSWORD: "$PG_PWD"
      POSTGRES_DB: "$PG_DB"
  migrator:
    container_name: migrate
    image: migrate/migrate
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "postgresql://$PG_USER:$PG_PWD@host.docker.internal:5432/$PG_DB?sslmode=disable"
      - "up"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations