bind_addr = "localhost:8080"
log_level = "debug"
db_connection_string = "host=localhost dbname=apiserver user=user password=user"
migrations_folder = "./migrations"
session_key = "zkEniJIqhVDVel6wrXzMqimGb3Vj1tBHg5um5JlnpFUmpw4bSIGTasivCa6eqVhB"
jaeger_url = "http://localhost:14268/api/traces"