scrape_configs:
  - job_name: myapp
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8080

# docker build -t my-prom .
# docker run -d -p 9090:9090 my-prom